### ISSUE TITLE
Duplikerende kode

### ISSUE THREAD

**Issue by Jenevo** [Dieuer/P2-2020-RS#101]
https://github.com/Dieuer/P2-2020-RS/blob/fbaa097ca75be3f042bbb7d9f417e7564e27d622/Src/Backend/DataConverters/convertToBinaryRepresentation.js#L114-L145

convertToBinaryRepresentation og metadataNumericBinaryConverter har rigtig meget kode, som er præcis ens, så vidt jeg kan se? Dette tager nok lidt længere tid at checke ville jeg gætte på

**Comment by Brandhoej** [comment]
De er ens. Mulig commit fejl da det er nondestructive. Sletter convertToBinaryRep. da jeg synes metadataNumericBinaryConverter navnet giver mere mening.

**Comment by Brandhoej** [comment]
Forskellen blandt de to er faktisk kun to funktioner (...andWrite, and ...read, convertToBinaryRepresentation ) alt andet er ens. Jeg synes dog at vi har en funktion der læser som kan findes i metedataReader. Jeg undergøer.

**Comment by Brandhoej** [comment]
Sletter readIthMovieBinaryMetadataArray fra convertToBinaryRepresentation  da den er i metadataReader og så sletter jeg metadataNumericBinaryConverter  da de er næsten ens nu. Men readIthMovieBinaryMetadataArray er lidt bedre grundet ...andWrite funktionen
