### ISSUE TITLE
Beskriv at cmp funktionen skal returnere 1 hvis de to værdier matcher, og ellers 0 

### ISSUE THREAD

**Issue by Sijmon** [Dieuer/P2-2020-RS#66]
https://github.com/Dieuer/P2-2020-RS/blob/d460d598d37e65b7e2ab388294b8a956205562ad/Src/Backend/ArrayExtensionFunctions.js#L51-L80

**Comment by Brandhoej** [comment]
Rigtig godt set. +1

**Comment by Brandhoej** [comment]
Jeg tager det tilbage -1. Det står allerede i komentareren.
"The compare function to pass each correspond element to (this[i], other[i]): boolean"
Læg mærke til : boolean
