### ISSUE TITLE
Const?

### ISSUE THREAD

**Issue by Jenevo** [Dieuer/P2-2020-RS#78]
https://github.com/Dieuer/P2-2020-RS/blob/d460d598d37e65b7e2ab388294b8a956205562ad/Src/Backend/ProfileHandler.js#L3

Skal denne være en const?

**Comment by DaaseAllan** [comment]
Nej, da det er et "library" af funtioner som vi alle gerne vil bruge, i stedet for bare en enkelt funtion.
