### ISSUE TITLE
Måske tilføje en kommentar om rest operatoren (...)

### ISSUE THREAD

**Issue by Dieuer** [Dieuer/P2-2020-RS#86]
https://github.com/Dieuer/P2-2020-RS/blob/20e9bd963a7272b2691380d9bf83d335165a9d1c/Src/Backend/ProfileHandler.js#L19

**Comment by Brandhoej** [comment]
Det er ikke REST operatoreren. Det er spread operatoren som der bliver brugt lige der.

**Comment by Brandhoej** [comment]
Jeg synes ikke vi skal lave en kommentar til alle steder en operator bliver brugt.
