### ISSUE TITLE
Behøves man denne const?

### ISSUE THREAD

**Issue by Jenevo** [Dieuer/P2-2020-RS#99]
https://github.com/Dieuer/P2-2020-RS/blob/fbaa097ca75be3f042bbb7d9f417e7564e27d622/Src/Backend/DataConverters/convertToBinaryRepresentation.js#L130

Er det ikke okay, bare at skrive .sum, når den bruges i if-statementet lidt længere nede?

**Comment by Brandhoej** [comment]
Nej. Sum bliver også brugt i Error msg
